### ISSUE TITLE
Overall design discusses

### ISSUE THREAD

**Issue by xplorld** [dyweb/sundial#1]
# scope

Should we copy WakaTime server exactly as-is, or do something different?

# Language

Python, Go, Rust, Cpp, or else?

# Architecture

MySQL + Influx + Sundial server?

Do we support distributed service? failure? scaling?

# Operation

public accessible service? Friends-sized service?

# Investment and IPO

When will we be rich?

**Comment by gaocegege** [comment]
I think we could extend wakatime's API but we should be compatible with current API.

I recommend Golang since it meets the demand for this project.

**Comment by at15** [comment]
+1 for go, we have many half baken go library i.e. https://github.com/dyweb/gommon https://github.com/dyweb/go.ice and it's good to have our own people eat our own ~~dog~~ food

**Comment by gaocegege** [comment]
Go + InfluxDB + MongoDB is preferred, thus I will use this stack.
