### ISSUE TITLE
remove gosimple from gometalinter

### ISSUE THREAD

**Issue by xplorld** [dyweb/sundial#19]
In https://github.com/alecthomas/gometalinter/issues/576, gometalinter removed support for gosimple as it is deprecated in favor of staticcheck. This causes us failing the Travis CI test for `unknown linters: gosimple`. Removing this from configuration should fix the travis CI errors.

**Comment by xplorld** [comment]
It seems it works on `1.10` but not on `1.9`. I don't know why. Could you shed some light on that? @gaocegege @at15

**Comment by at15** [comment]
@xplorld we can drop support for go1.9, just use go1.10 go1.11 and tip, only the two latest two version is actively maintained, besides sundail is an application instead of library
